---
- name: consul-template setup
  hosts: all
  become: true
  gather_facts: false

  vars:

  tasks:
    - name: create conf directory
      ansible.builtin.file:
        path: /etc/consul-template.d
        state: directory
        owner: root
        group: root
        mode: '0744'

    - name: add Hashicorp repository
      ansible.builtin.yum_repository:
        name: Hashicorp-Stable
        description: Hashicorp stable repo
        baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        gpgcheck: true

    - name: install consul-template package
      ansible.builtin.yum:
        name: consul-template

    - name: copy consul-template service file
      ansible.builtin.copy:
        backup: true
        dest: /etc/systemd/system/consul-template.service
        content: |
          [Unit]
          Description=consul-template
          Requires=network-online.target
          After=network-online.target consul.service vault.service

          [Service]
          EnvironmentFile=-/etc/sysconfig/consul-template
          Restart=on-failure
          ExecStart=/usr/bin/consul-template $OPTIONS -config=/etc/consul-template.d
          ExecReload=/bin/kill -HUP $MAINPID
          KillSignal=SIGINT

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: start consul-template service
      ansible.builtin.service:
        name: consul-template.service
        state: started
        enabled: true

  post_tasks:
    - name: verify installed consul-template package
      ansible.builtin.shell:
        cmd: set -o pipefail; yum list installed | grep consul-template\.
      changed_when: false
      register: result
      failed_when: result.rc != 0

    - name: print installed version
      ansible.builtin.debug:
        var: result.stdout

    - name: verify started consul-template service
      ansible.builtin.service:
        name: consul-template.service
        state: started
        enabled: true
      check_mode: true
      register: result
      failed_when: result.changed

  handlers:
    - name: restart consul-template service
      service:
        name: consul-template.service
        state: restarted
