---
- name: security
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: set kernel parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { name: net.ipv6.conf.all.disable_ipv6, value: 1 }
        - { name: net.ipv6.conf.default.disable_ipv6, value: 1 }
        - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
        - { name: net.ipv4.ip_forward, value: 0 }
        - { name: net.ipv4.conf.all.rp_filter, value: 1 }
        - { name: net.ipv4.conf.default.rp_filter, value: 1 }
        - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
        - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
        - { name: net.ipv4.conf.all.log_martians, value: 1 }
        - { name: kernel.randomize_va_space, value: 2 }
      notify: reboot server

  handlers:
    - name: reboot server
      when: ansible_connection not in ["container", "docker", "community.docker.docker"]
      ansible.builtin.reboot:
