---
- name: minio setup
  hosts: all
  become: true
  gather_facts: false

  vars:
    minio_container_image: "minio/minio"

  pre_tasks:
    - name: install python-pip packages
      ansible.builtin.yum:
        name:
          - python3-pip

  tasks:
    - name: install docker python package
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose

    - name: create conf directory
      ansible.builtin.file:
        path: /etc/minio
        state: directory
        owner: root
        group: root
        mode: '0744'

    - name: copy docker-compose file
      ansible.builtin.copy:
        backup: true
        dest: /etc/minio/docker-compose.yml
        content: |
          version: "3"

          services:
            minio:
              image: {{ minio_container_image }}
              ports:
                - 9000:9000
                - 9001:9001
              volumes:
                - ./.data/minio/data:/export
                - ./.data/minio/config:/root/.minio
              environment:
                MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
                MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio123}
              command: server /export --console-address ":9001"
            createbuckets:
              image: minio/mc
              depends_on:
                - minio
              entrypoint: >
                /bin/sh -c "
                until (/usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ACCESS_KEY:-minio} ${MINIO_SECRET_KEY:-minio123}) do echo '...waiting...' && sleep 1; done;
                /usr/bin/mc mb myminio/${MINIO_BUCKET_NAME:-mybucket};
                /usr/bin/mc policy download myminio/${MINIO_BUCKET_NAME:-mybucket};
                exit 0;
                "
        owner: root
        group: root
        mode: "0644"
      notify: restart containers

    - name: start containers
      community.docker.docker_compose:
        project_src: /etc/minio

  post_tasks:
    - name: verify started minio contailner
      ansible.builtin.command:
        cmd: docker container ls
      changed_when: false
      register: result
      failed_when: "'minio/minio' not in result.stdout"

  handlers:
    - name: restart containers
      community.docker.docker_compose:
        project_src: /etc/minio
        restarted: true
