---
- name: swatch setup
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: install epel repository
      yum:
        name: epel-release

    - name: install swatch package
      ansible.builtin.yum:
        name: swatch

    - name: create swatch conf directory
      ansible.builtin.file:
        path: /etc/swatch
        state: directory
        mode: '0755'

    - name: copy sample conf
      ansible.builtin.copy:
        dest: /etc/swatch/sample.conf
        content: |
          # logfile /var/log/yum.log

          watchfor /Installed:/
            echo
        mode: "0644"

    - name: copy swatchctl
      ansible.builtin.copy:
        dest: /usr/local/bin/swatchctl
        content: |
          #!/bin/bash
          #
          # swatch ctl
          #
          # description: swatch start/stop script

          PATH=/sbin:/usr/local/bin:/bin:/usr/bin

          mkdir -p /var/log/swatch

          start() {
               # Start daemons.
               ls /var/run/swatch_*.pid > /dev/null 2>&1
               if [ $? -ne 0 ]; then
                    echo -n "Starting swatch"
                    pno=0
                    for conf in /etc/swatch/*.conf
                    do
                         pno=`expr $pno + 1`
                         WATCHLOG=`grep "^# logfile" $conf | awk '{ print $3 }'`
                         swatch --config-file $conf --tail-file $WATCHLOG \
                         --script-dir=/tmp --daemon --pid-file /var/run/swatch_$pno.pid \
                         >> /var/log/swatch/swatch.log 2>&1
                         RETVAL=$?
                         [ $RETVAL != 0 ] && return $RETVAL
                    done
                    echo
                    [ $RETVAL = 0 ] && touch /var/lock/subsys/swatch
                    return $RETVAL
               else
                    echo "swatch is already started"
               fi
          }

          stop() {
               # Stop daemons.
               ls /var/run/swatch_*.pid > /dev/null 2>&1
               if [ $? -eq 0 ]; then
                    echo -n "Shutting down swatch"
                    for pid in /var/run/swatch_*.pid
                    do
                         kill $(cat $pid)
                         rm -f $pid
                    done
                    echo
                    rm -f /var/lock/subsys/swatch /tmp/.swatch_script.*
               else
                    echo "swatch is not running"
               fi
          }

          case "$1" in
               start)
                       start
                       ;;
               stop)
                       stop
                       ;;
               *)
                    echo "Usage: swatch {start|stop}"
                    exit 1
          esac

          exit $RETVAL
        mode: 0755

    - name: copy swatchd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/swatchd.service
        content: |
          [Unit]
          Description=swatch service

          [Service]
          Type=forking
          ExecStart=/usr/local/bin/swatchctl start
          ExecStop=/usr/local/bin/swatchctl stop
          Restart=always
          StartLimitBurst=0

          [Install]
          WantedBy=multi-user.target
        mode: 0644

    - name: daemon reload
      ansible.builtin.systemd: daemon_reload=yes

    - name: start swatch service
      ansible.builtin.service:
        name: swatchd.service
        state: started
        enabled: true

  post_tasks:
    - name: verify installed swatch package
      ansible.builtin.shell:
        cmd: set -o pipefail; yum list installed | grep swatch\\.
      changed_when: false
      register: result
      failed_when: result.rc != 0

    - name: print installed version
      ansible.builtin.debug:
        var: result.stdout

    - name: verify started swatch service
      ansible.builtin.service:
        name: swatch.service
        state: started
        enabled: true
      check_mode: true
      register: result
      failed_when: result.changed
