---
- name: postgresql setup
  hosts: all
  become: true
  gather_facts: false

  vars:
    pgsql_version: "15"

  pre_tasks:
    - name: update ca-certificates  # noqa package-latest
      ansible.builtin.yum:
        name: ca-certificates
        state: latest

    - name: install epel repository
      ansible.builtin.yum:
        name: epel-release

  tasks:
    - name: add postgresql repository
      ansible.builtin.yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

    - name: install postgresql package
      ansible.builtin.yum:
        name: "postgresql{{ pgsql_version }}-server"

    - name: initialize database cluster
      ansible.builtin.command:
        cmd: "postgresql-{{ pgsql_version }}-setup initdb"
        creates: "/var/lib/pgsql/{{ pgsql_version }}/data/PG_VERSION"

    - name: start postgresql service
      ansible.builtin.service:
        name: "postgresql-{{ pgsql_version }}.service"
        state: started
        enabled: true

  post_tasks:
    - name: verify installed postgresql package
      ansible.builtin.shell:
        cmd: set -o pipefail; yum list installed | grep postgresql{{ pgsql_version }}-server\\.
      changed_when: false
      register: result
      failed_when: result.rc != 0

    - name: print installed version
      ansible.builtin.debug:
        var: result.stdout

    - name: verify started postgresql
      ansible.builtin.service:
        name: "postgresql-{{ pgsql_version }}.service"
        state: started
        enabled: true
      check_mode: true
      register: result
      failed_when: result.changed
