---
- name: clamav install
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: install epel repository
      ansible.builtin.yum:
        name: epel-release

    - name: install clamav package
      ansible.builtin.yum:
        name: clamav

    - name: init clamav database
      command: freshclam
      args:
        creates: /var/lib/clamav/freshclam.dat

  post_tasks:
    - name: verify installed clamav package
      ansible.builtin.shell:
        cmd: set -o pipefail; yum list installed | grep clamav\\.
      changed_when: false
      register: result
      failed_when: result.rc != 0

    - name: print installed version
      ansible.builtin.debug:
        var: result.stdout

    - name: verify freshclam.data exist
      ansible.builtin.wait_for:
        path: /var/lib/clamav/freshclam.dat
        state: present
        timeout: 5
