---
- name: fail2ban status
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: get jail list
      ansible.builtin.shell:
        cmd: fail2ban-client status | grep "Jail list" | sed -E "s/^[^:]+:[ \t]+//" | sed "s/,//g"
      changed_when: false
      register: jail_list

    - name: get jail status
      ansible.builtin.command:
        cmd: "fail2ban-client status {{ item }}"
      changed_when: false
      register: result
      loop: "{{ jail_list.stdout | split }}"

    - name: print result
      ansible.builtin.debug:
        var: result.results | map(attribute='stdout_lines') | list
