---
- name: selinux configuration
  hosts: all
  become: true
  gather_facts: false

  vars:
    selinux_enforcing: true

  pre_tasks:
    - name: check releasever
      ansible.builtin.shell:
        cmd: cat /etc/os-release | grep VERSION_ID | sed -e 's/.*"\(.*\)"/\1/'
      changed_when: false
      failed_when: false
      register: result

    - name: set releasever as fact
      ansible.builtin.set_fact:
        releasever: "{{ result.stdout[0] }}"

    - name: install selinux packages
      ansible.builtin.yum:
        name:
          - "{{ 'python3-libselinux' if releasever != '7' else 'libselinux-python' }}"
          - setroubleshoot-server

  tasks:
    - name: set selinux state as fact
      ansible.builtin.set_fact:
        selinux_state: "{{ 'enforcing' if selinux_enforcing else 'permissive' }}"

    - name: set selinux state to '{{ selinux_state }}'
      ansible.posix.selinux:
        state: "{{ selinux_state }}"
        policy: targeted
      notify: reboot server

  post_tasks:
    - name: verify selinux '{{ selinux_state }}'
      ansible.builtin.command:
        cmd: getenforce
      changed_when: false
      register: result
      failed_when: selinux_state != result.stdout | lower

  handlers:
    - name: reboot server
      ansible.builtin.reboot:
