---
- name: /etc/hosts setup
  hosts: all
  become: true
  gather_facts: false

  vars:
    sys_net_dev: "eth1"
    sys_local_domain: "localdomain"
    sys_etc_hosts: "{{ ansible_play_hosts | sort }}"

  tasks:
    - name: get ip address
      ansible.builtin.shell:
        cmd: "ip address show dev {{ sys_net_dev }} | grep -oP '(?<=inet )\\S+(?=/)'"
      changed_when: false
      register: result

    - name: ip address as fact
      ansible.builtin.set_fact:
        ipv4_address: "{{ result.stdout }}"

    - name: ommit loopback address
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ^(127\.\d\.\d\.\d\s+{{ inventory_hostname }}.*)
        line: '#\1'
        backrefs: true
        backup: true

    - name: add hosts address
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {% for item in sys_etc_hosts %}
          {{ hostvars[item].ipv4_address }} {{ item }} {{ item }}.{{ sys_local_domain }}
          {% endfor %}
        backup: true

  post_tasks:
    - name: verify host all entory
      ansible.builtin.command: getent hosts
      changed_when: false
      register: result
      failed_when: result.rc != 0

    - name: print entory
      ansible.builtin.debug:
        var: result.stdout_lines

    - name: verify lookup host entory
      ansible.builtin.command: getent hosts {{ inventory_hostname }}
      changed_when: false
      register: result
      failed_when: result.rc != 0
