---
- name: firewalld configration
  hosts: all
  become: true
  gather_facts: false

  vars:
    firewalld_services:
      - ssh
      - http
      - https

  pre_tasks:
    - name: start firewalld service
      ansible.builtin.service:
        name: firewalld.service
        state: started
        enabled: true

  tasks:
    - name: populate service facts
      ansible.builtin.command:
        cmd: "firewall-cmd --list-services --zone=public --permanent"
      changed_when: false
      register: service_facts

    - name: remove services
      ansible.posix.firewalld:
        zone: public
        service: "{{ item }}"
        permanent: true
        state: disabled
      when: item not in firewalld_services
      loop: "{{ service_facts.stdout.split(' ') }}"
      notify: restart firewalld service

    - name: add services
      ansible.posix.firewalld:
        zone: public
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ firewalld_services }}"
      notify: restart firewalld service

  post_tasks:
    - name: verify enabled services
      ansible.builtin.command:
        cmd: "firewall-cmd --list-services --zone=public --permanent"
      changed_when: false
      register: result

    - name: fail
      ansible.builtin.fail:
      when: item not in result.stdout
      loop: "{{ firewalld_services }}"

    - name: print services
      ansible.builtin.debug:
        var: result.stdout

  handlers:
    - name: restart firewalld service
      ansible.builtin.service:
        name: firewalld.service
        state: restarted
