---
- name: root user protection
  hosts: all
  become: true
  gather_facts: false

  vars:
    login_shell: "/sbin/nologin"

  tasks:
    - name: change shell to '{{ login_shell }}'
      ansible.builtin.user:
        name: root
        shell: "{{ login_shell }}"

  post_tasks:
    - name: verify shell '{{ login_shell }}'
      ansible.builtin.command:
        cmd: getent passwd root
      changed_when: false
      register: result
      failed_when: not login_shell in result.stdout

