---
# ref
# - https://www.belbel.or.jp/opensuse-manuals_ja/cha-audit-comp.html
#
- name: auditd setup
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: set auditd rules
      ansible.builtin.blockinfile:
        path: /etc/audit/rules.d/audit.rules
        block: |
          # audit log files and configuration files
          -w /var/log/audit/
          -w /var/log/audit/audit.log
          -w /var/log/audit/audit_log.1
          -w /var/log/audit/audit_log.2
          -w /var/log/audit/audit_log.3
          -w /var/log/audit/audit_log.4
          -w /etc/audit/auditd.conf -p wa
          -w /etc/audit/audit.rules -p wa

          # security configurarion files and databases
          -w /etc/group -p wa
          -w /etc/passwd -p wa
          -w /etc/shadow
          -w /etc/securetty
          -w /etc/localtime -p wa
        backup: true
      notify: restart auditd service

  handlers:
    - name: restart auditd service # noqa command-instead-of-module
      ansible.builtin.command:
        cmd: service auditd restart

  post_tasks:
    - name: verify started auditd
      ansible.builtin.service:
        name: auditd
        state: started
        enabled: true
      check_mode: true
      register: result
      failed_when: result.changed

    - name: verify auditctl list
      ansible.builtin.command:
        cmd: auditctl -l
      changed_when: false
      register: result
      failed_when: item not in result.stdout
      loop:
        # audit log files and configuration files
        - -w /var/log/audit/
        - -w /var/log/audit/audit.log
        - -w /var/log/audit/audit_log.1
        - -w /var/log/audit/audit_log.2
        - -w /var/log/audit/audit_log.3
        - -w /var/log/audit/audit_log.4
        - -w /etc/audit/auditd.conf -p wa
        - -w /etc/audit/audit.rules -p wa
        # security configurarion files and databases
        - -w /etc/group -p wa
        - -w /etc/passwd -p wa
        - -w /etc/shadow
        - -w /etc/securetty
        - -w /etc/localtime -p wa
