---
- name: root user protection
  hosts: all
  become: true
  gather_facts: false

  vars:
    user_shell: "/sbin/nologin"

  tasks:
    - name: change shell to '{{ user_shell }}'
      ansible.builtin.user:
        name: root
        shell: "{{ user_shell }}"

  post_tasks:
    - name: verify shell '{{ user_shell }}'
      ansible.builtin.command:
        cmd: getent passwd root
      changed_when: false
      register: result
      failed_when: not user_shell in result.stdout
